orders:
  commands:
    topic:
      name: orders-commands
  events:
    topic:
      name: orders-events
payments:
  commands:
    topic:
      name: payments-commands
  events:
    topic:
      name: payments-events
products:
  commands:
    topic:
      name: products-commands
  events:
    topic:
      name: products-events

server:
  port: 8080

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    open-in-view: false
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9094
      - localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
    consumer:
      group-id: orders-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.appsdeveloperblog.core.*
