app:
  topic-name: product-created-events-topic

server:
  # port could be 0, which means any available port
  port: 8080

spring:
  application:
    name: products-microservice

  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9094
      # serializer is used to serialize key values to byte array before sending them over the network
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # spring.kafka.producer.acks=[all|1|0] for producer acknowledgement
      # 1 means one acknowledgement from kafka producer, which is the default value
      # all means that producer will wait for acknowledgement from all in-sync replicas
      acks: all
