logging:
  level:
    org:
      apache:
        kafka:
          clients:
            producer:
              internals:
                TransactionManager: TRACE
      springframework:
        kafka:
          transaction: TRACE
        transaction: TRACE

server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
      # enable kafka transaction support, and assign unique transaction id prefix
      transaction-id-prefix: transfer-service-${random.value}-

withdraw-money-topic: withdraw-money-topic
deposit-money-topic: deposit-money-topic
