services:
  kafka-1:
    image: 'bitnami/kafka:3.9.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=1
      # The presence of KAFKA_KRAFT_CLUSTER_ID and KAFKA_CFG_PROCESS_ROLES confirms this Kafka instance is running in KRaft mode, not using Zookeeper.
      - KAFKA_KRAFT_CLUSTER_ID=NxBKhbUOROe9AEmaKO_tsg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # format: node_id@host_name:port
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      # format: listener_name://[host_name]:port_number
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      # Configures how the Kafka broker advertises itself to clients and other brokers.
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - TZ=Europe/Brussels
    volumes:
      - ./kafka-1:/bitnami/kafka
