server:
  port: 8086

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: amount-widthrawal-event
      properties:
        spring.json.trusted.packages: com.appsdeveloperblog.*
      # to read committed message only to guarantee the transactional behaviour.
      isolation-level: read_committed
